import React, { useState, useRef, useEffect } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  TextInput,
  StyleSheet,
  Animated,
  Modal,
  FlatList,
  Platform,
  Pressable,
  KeyboardAvoidingView,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useColors } from "@/hooks/useColors";

interface FaqMessage {
  id: string;
  role: "user" | "bot";
  content: string;
}

const FAQS: { question: string; answer: string; keywords: string[] }[] = [
  {
    question: "How do I start an interview?",
    answer:
      "Tap the Start Interview button on the Dashboard. You'll then choose your interview type (Technical, HR, or Mixed), difficulty level (Easy, Medium, or Hard), your target job role, optional company name, and skills to focus on.",
    keywords: ["start", "begin", "interview", "new", "create"],
  },
  {
    question: "What types of interviews are available?",
    answer:
      "There are three interview types:\n• Technical — coding, algorithms, data structures, system design\n• HR — behavioral, situational, and soft-skill questions\n• Mixed — a blend of both technical and HR questions",
    keywords: ["type", "types", "technical", "hr", "mixed", "behavioral", "kind"],
  },
  {
    question: "How are my answers scored?",
    answer:
      "Each answer is evaluated by AI and given a score out of 10. After completing all 10 questions, tap Evaluate to get your full report with:\n• Per-question scores and ideal answers\n• Strengths and weaknesses\n• Overall performance rating\n• Improvement suggestions",
    keywords: ["score", "scoring", "evaluated", "evaluation", "rating", "report", "grade", "result"],
  },
  {
    question: "What is the AI Coach tab?",
    answer:
      "The AI Coach is a full conversational assistant powered by GPT. It can:\n• Explain technical concepts\n• Help you craft better answers\n• Give mock interview practice\n• Offer company-specific tips\n• Advise on salary negotiation\n\nUnlike this FAQ bot, the AI Coach handles open-ended questions on any interview topic.",
    keywords: ["ai coach", "coach", "chat", "assistant", "gpt", "ai"],
  },
  {
    question: "How do I view my past sessions?",
    answer:
      "Tap the History tab in the bottom navigation. You'll see all your past interview sessions with their status, score, and date. Tap any session to view the full detail including all questions, your answers, and ideal answers.",
    keywords: ["history", "past", "previous", "sessions", "old"],
  },
  {
    question: "How do I sign out?",
    answer:
      "Go to the Profile tab in the bottom navigation, then scroll down and tap Sign Out. You'll be taken back to the sign-in screen.",
    keywords: ["sign out", "logout", "log out", "signout", "exit", "leave"],
  },
  {
    question: "How many questions are in each interview?",
    answer:
      "Each interview session has exactly 10 questions generated by AI based on your selected type, difficulty, job role, company, and skills.",
    keywords: ["how many", "questions", "number", "count", "10"],
  },
  {
    question: "Can I change difficulty?",
    answer:
      "Yes! When starting a new interview, you can choose from three difficulty levels:\n• Easy — fundamental concepts, good for practice\n• Medium — standard interview level\n• Hard — senior/advanced level questions",
    keywords: ["difficulty", "easy", "medium", "hard", "level", "change"],
  },
  {
    question: "What is the reference insight on each question?",
    answer:
      "During your interview session, each question shows a Reference Insight panel (the lightbulb icon). It provides:\n• Related topic area\n• Similar questions you might encounter\n• Company tags (companies known for asking this type of question)\n\nUse it to guide your answer without giving away the ideal answer.",
    keywords: ["reference", "insight", "hint", "tip", "lightbulb", "guide"],
  },
  {
    question: "Is my data private?",
    answer:
      "Yes. Your interview sessions and answers are stored securely and tied to your account only. Other users cannot access your data. Your answers are sent to OpenAI's API for evaluation but are not used to train their models.",
    keywords: ["private", "privacy", "data", "secure", "security", "safe"],
  },
  {
    question: "Can I use this offline?",
    answer:
      "No — AI Smart Interview Prep requires an internet connection. The AI question generation, answer evaluation, and AI Coach all rely on real-time API calls.",
    keywords: ["offline", "internet", "connection", "without internet"],
  },
  {
    question: "Can I retake an interview?",
    answer:
      "Yes! Every interview you start creates a new independent session. Just tap Start Interview again from the Dashboard to create a fresh session with new AI-generated questions.",
    keywords: ["retake", "redo", "again", "repeat", "another"],
  },
  {
    question: "How long does an interview take?",
    answer:
      "It depends on your pace and difficulty level. Typically:\n• Easy — 10–20 minutes\n• Medium — 20–35 minutes\n• Hard — 30–50 minutes\n\nThere is no time limit per question, so take as long as you need.",
    keywords: ["long", "duration", "time", "minutes", "limit", "how long"],
  },
  {
    question: "What happens if I skip a question?",
    answer:
      "You can move to the next question without answering, but skipped questions won't receive a score. For the best report, try to answer all 10 questions before evaluating.",
    keywords: ["skip", "blank", "leave", "unanswered", "pass"],
  },
  {
    question: "How do I track my progress?",
    answer:
      "The Dashboard shows your overall stats — total sessions, average score, and recent activity. The History tab lets you review every past session in detail to see how you've improved over time.",
    keywords: ["progress", "track", "improve", "stats", "statistics", "dashboard"],
  },
  {
    question: "What companies' questions are covered?",
    answer:
      "The AI generates questions tagged with real companies like Google, Amazon, Microsoft, Meta, Apple, and many more. You can also enter a specific company name when setting up your interview to get more targeted questions.",
    keywords: ["company", "companies", "google", "amazon", "microsoft", "meta", "apple", "faang"],
  },
  {
    question: "How do I reset my password?",
    answer:
      "On the sign-in screen, tap Forgot Password (if shown) or use the Sign In with Google option to access your account. Password reset emails are managed through your Clerk account settings.",
    keywords: ["password", "reset", "forgot", "change password"],
  },
  {
    question: "Can I use this on multiple devices?",
    answer:
      "Yes! Your account and all interview data are stored in the cloud. Sign in with the same credentials on any device and all your sessions and history will be available.",
    keywords: ["devices", "multiple", "phone", "tablet", "cross", "sync"],
  },
  {
    question: "What job roles can I practice for?",
    answer:
      "Any role! When setting up an interview, just type in your target job role — Software Engineer, Data Scientist, Product Manager, DevOps Engineer, UX Designer, etc. The AI will generate relevant questions for that role.",
    keywords: ["role", "job", "position", "engineer", "developer", "manager", "designer"],
  },
  {
    question: "What is shown in the performance report?",
    answer:
      "After evaluation, your report shows:\n• Overall score and accuracy %\n• Time taken\n• Per-question breakdown with your answer, ideal answer, score, and feedback\n• Key strengths and weaknesses\n• Personalized improvement suggestions",
    keywords: ["report", "performance", "results", "breakdown", "feedback", "ideal answer"],
  },
];

const QUICK_QUESTIONS = [
  "How do I start an interview?",
  "How is scoring done?",
  "What is AI Coach?",
  "How to view history?",
];

function findAnswer(query: string): string {
  const lower = query.toLowerCase();
  const match = FAQS.find((faq) =>
    faq.keywords.some((kw) => lower.includes(kw))
  );
  if (match) return match.answer.replace(/\*\*(.*?)\*\*/g, "$1");
  return "I'm not sure about that. For open-ended interview questions and coaching, head to the AI Coach tab — it can help with anything! Or try rephrasing your question here.";
}

export default function FaqBot() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<FaqMessage[]>([
    {
      id: "welcome",
      role: "bot",
      content: "Hi! 👋 I'm the Help Bot. I can answer questions about how this app works.\n\nAsk me anything, or pick a topic below!",
    },
  ]);
  const [input, setInput] = useState("");
  const flatListRef = useRef<FlatList>(null);
  const scaleAnim = useRef(new Animated.Value(0)).current;
  const pulseAnim = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, { toValue: 1.06, duration: 1400, useNativeDriver: true }),
        Animated.timing(pulseAnim, { toValue: 1, duration: 1400, useNativeDriver: true }),
      ])
    ).start();
  }, []);

  useEffect(() => {
    Animated.spring(scaleAnim, {
      toValue: open ? 1 : 0,
      useNativeDriver: true,
      tension: 80,
      friction: 10,
    }).start();
  }, [open]);

  const handleSend = (text?: string) => {
    const content = (text ?? input).trim();
    if (!content) return;
    setInput("");

    const userMsg: FaqMessage = { id: Date.now().toString(), role: "user", content };
    const answer = findAnswer(content);
    const botMsg: FaqMessage = { id: (Date.now() + 1).toString(), role: "bot", content: answer };

    setMessages((prev) => [...prev, userMsg, botMsg]);
    setTimeout(() => flatListRef.current?.scrollToEnd({ animated: true }), 150);
  };

  const showQuicks = messages.length === 1;

  return (
    <>
      <Animated.View
        style={[
          styles.fabWrap,
          {
            bottom: insets.bottom + 88,
            transform: [{ scale: pulseAnim }],
          },
        ]}
        pointerEvents="box-none"
      >
        <TouchableOpacity
          onPress={() => setOpen(true)}
          activeOpacity={0.85}
          style={styles.fab}
        >
          <LinearGradient
            colors={["#f59e0b", "#ef4444"]}
            style={styles.fabGradient}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
          >
            <Feather name="help-circle" size={22} color="#fff" />
          </LinearGradient>
        </TouchableOpacity>
        <View style={[styles.fabBadge, { backgroundColor: colors.success }]}>
          <Text style={styles.fabBadgeText}>FAQ</Text>
        </View>
      </Animated.View>

      <Modal
        visible={open}
        transparent
        animationType="slide"
        onRequestClose={() => setOpen(false)}
        statusBarTranslucent
      >
        <Pressable style={styles.backdrop} onPress={() => setOpen(false)} />
        <KeyboardAvoidingView
          behavior={Platform.OS === "ios" ? "padding" : "height"}
          style={styles.sheetWrap}
          keyboardVerticalOffset={0}
        >
          <View
            style={[
              styles.sheet,
              {
                backgroundColor: colors.background,
                paddingBottom: insets.bottom + 12,
              },
            ]}
          >
            <View style={[styles.sheetHandle, { backgroundColor: colors.border }]} />

            <View style={[styles.sheetHeader, { borderBottomColor: colors.border }]}>
              <LinearGradient
                colors={["#f59e0b", "#ef4444"]}
                style={styles.sheetIcon}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
              >
                <Feather name="help-circle" size={16} color="#fff" />
              </LinearGradient>
              <View style={{ flex: 1 }}>
                <Text style={[styles.sheetTitle, { color: colors.foreground }]}>Help Bot</Text>
                <Text style={[styles.sheetSub, { color: colors.mutedForeground }]}>
                  Answers questions about this app
                </Text>
              </View>
              <TouchableOpacity
                onPress={() => setOpen(false)}
                style={[styles.closeBtn, { backgroundColor: colors.muted }]}
                hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
              >
                <Feather name="x" size={16} color={colors.mutedForeground} />
              </TouchableOpacity>
            </View>

            <FlatList
              ref={flatListRef}
              data={messages}
              keyExtractor={(m) => m.id}
              style={styles.chatList}
              contentContainerStyle={{ gap: 10, paddingBottom: 8 }}
              showsVerticalScrollIndicator={false}
              ListFooterComponent={
                showQuicks ? (
                  <View style={styles.quicksWrap}>
                    <Text style={[styles.quicksLabel, { color: colors.mutedForeground }]}>Quick topics:</Text>
                    {QUICK_QUESTIONS.map((q) => (
                      <TouchableOpacity
                        key={q}
                        style={[styles.quickChip, { backgroundColor: colors.card, borderColor: colors.border }]}
                        onPress={() => handleSend(q)}
                        activeOpacity={0.75}
                      >
                        <Feather name="chevron-right" size={13} color={colors.primary} />
                        <Text style={[styles.quickText, { color: colors.foreground }]}>{q}</Text>
                      </TouchableOpacity>
                    ))}
                  </View>
                ) : null
              }
              renderItem={({ item }) => {
                const isUser = item.role === "user";
                return (
                  <View style={[styles.msgRow, isUser ? styles.msgRowUser : styles.msgRowBot]}>
                    {!isUser && (
                      <LinearGradient
                        colors={["#f59e0b", "#ef4444"]}
                        style={styles.botAvatar}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 1 }}
                      >
                        <Feather name="help-circle" size={11} color="#fff" />
                      </LinearGradient>
                    )}
                    <View
                      style={[
                        styles.msgBubble,
                        isUser
                          ? [styles.userMsg, { backgroundColor: colors.primary }]
                          : [styles.botMsg, { backgroundColor: colors.card, borderColor: colors.border }],
                      ]}
                    >
                      <Text
                        style={[
                          styles.msgText,
                          { color: isUser ? colors.primaryForeground : colors.foreground },
                        ]}
                      >
                        {item.content}
                      </Text>
                    </View>
                  </View>
                );
              }}
            />

            <View style={[styles.inputRow, { borderTopColor: colors.border }]}>
              <View style={[styles.inputBox, { backgroundColor: colors.card, borderColor: colors.border }]}>
                <TextInput
                  style={[styles.input, { color: colors.foreground }]}
                  value={input}
                  onChangeText={setInput}
                  placeholder="Ask about the app..."
                  placeholderTextColor={colors.mutedForeground}
                  returnKeyType="send"
                  onSubmitEditing={() => handleSend()}
                />
                <TouchableOpacity
                  style={[styles.sendBtn, { backgroundColor: input.trim() ? colors.primary : colors.muted }]}
                  onPress={() => handleSend()}
                  disabled={!input.trim()}
                  activeOpacity={0.85}
                >
                  <Feather
                    name="send"
                    size={14}
                    color={input.trim() ? colors.primaryForeground : colors.mutedForeground}
                  />
                </TouchableOpacity>
              </View>
            </View>
          </View>
        </KeyboardAvoidingView>
      </Modal>
    </>
  );
}

const styles = StyleSheet.create({
  fabWrap: {
    position: "absolute",
    left: 16,
    zIndex: 100,
  },
  fab: { shadowColor: "#f59e0b", shadowOpacity: 0.4, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 8 },
  fabGradient: { width: 52, height: 52, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  fabBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 8,
  },
  fabBadgeText: { fontSize: 9, fontFamily: "Inter_700Bold", color: "#fff" },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.45)" },
  sheetWrap: { flex: 1, justifyContent: "flex-end" },
  sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: "85%", minHeight: 480 },
  sheetHandle: { width: 36, height: 4, borderRadius: 2, alignSelf: "center", marginTop: 10, marginBottom: 4 },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  sheetIcon: { width: 36, height: 36, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  sheetTitle: { fontSize: 15, fontFamily: "Inter_700Bold" },
  sheetSub: { fontSize: 11, fontFamily: "Inter_400Regular", marginTop: 1 },
  closeBtn: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  chatList: { flex: 1, paddingHorizontal: 14, paddingTop: 12 },
  msgRow: { flexDirection: "row", alignItems: "flex-end", gap: 7 },
  msgRowUser: { justifyContent: "flex-end" },
  msgRowBot: { justifyContent: "flex-start" },
  botAvatar: { width: 24, height: 24, borderRadius: 8, alignItems: "center", justifyContent: "center", flexShrink: 0, marginBottom: 2 },
  msgBubble: { maxWidth: "80%", borderRadius: 16, padding: 11 },
  userMsg: { borderBottomRightRadius: 4 },
  botMsg: { borderWidth: StyleSheet.hairlineWidth, borderBottomLeftRadius: 4 },
  msgText: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 20 },
  quicksWrap: { marginTop: 12, gap: 7 },
  quicksLabel: { fontSize: 11, fontFamily: "Inter_500Medium" },
  quickChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
  },
  quickText: { fontSize: 13, fontFamily: "Inter_400Regular" },
  inputRow: { paddingHorizontal: 12, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 8,
  },
  input: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", paddingVertical: 5 },
  sendBtn: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" },
});
